### ISSUE TITLE
Production Window

### ISSUE THREAD

**Issue by kwakuduahc1** [pamtbaau/angular6-electron2-sqlite3-bootstrap4-webpack4#2]
Nice project. However the devtools window shows in production and i would turn that off in production as it does not make for good aesthetics. 

I cannot find the exact part of the app where it can be turned off so kindly help

**Comment by pamtbaau** [comment]
Thanks for pointing this out. The devtools should indeed not open in production. 

I forgot to remove some code in [index.js](https://github.com/pamtbaau/angular6-electron2-sqlite3-bootstrap4-webpack4/blob/master/index.js#L38) that bypasses this check for production.

I will clean it up.

**Comment by kwakuduahc1** [comment]
Thanks

**Comment by pamtbaau** [comment]
Fixed in ea50b80
