### ISSUE TITLE
CSS vs SCSS

### ISSUE THREAD

**Issue by kwakuduahc1** [pamtbaau/angular6-electron2-sqlite3-bootstrap4-webpack4#3]
Could you by default add a default css loader to the app. Not everybody likes or is familiar with SCSS and how to even bundle it in webpack.

**Comment by pamtbaau** [comment]
**css versus scss**
There is no need to learn scss to get started. One can add/import any valid css to the style.scss file. 

According the [Sass docs](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syntax):
>[...] SCSS (Sassy CSS) [...], is an extension of the syntax of CSS. This means that every valid CSS stylesheet is a valid SCSS file with the same meaning.

Hope this helps to get the non-savvy scss developers started.

**css-loader:**
Your suggestion might indeed help a few developers, but it is out of the scope of this project. This project is a dump of my experience and is meant to be a starter sample to get one up and running using the mentioned technologies. It is not meant to cater for all types of users and use-cases.

Thanks @kwakuduahc1 for your suggestions to improve this project. I appreciate it.

**Comment by kwakuduahc1** [comment]
Okay thanks for the explanation.
