### ISSUE TITLE
how to use node module fs & path in angular6?

### ISSUE THREAD

**Issue by dyh333** [pamtbaau/angular6-electron2-sqlite3-bootstrap4-webpack4#4]
hi, @pamtbaau . as the title, I found you use node module fs & path in angular6. and I tried it but when run npm run build it failed. so how you do it? btw, I used angular-cli tool but not webpack config. 
any is help, thanks.

**Comment by pamtbaau** [comment]
I feel like being a total noob on Javascript module loaders (commonjs, systemjs, etc.) and I have struggled a lot with loading Node's 'fs' and 'path' modules myself...

I have tried angular-cli before, but felt it was too boxed and needed Webpack itself to solve more complex configs. So, I can't tell you much on angular-cli and how to configure it. 

The js module resolution defined in my tsconfig.json is as follows:
```
"module": "commonjs",
"moduleResolution": "node",
```
and I import the node libraries as follows in 'src/app/app.component.ts':
```
import * as fs from 'fs';
import * as path from 'path';
```

Don't ask me why it works... it works for me...
